# NodeJS version
FROM node:16.3.0-alpine

# Create app directory
WORKDIR /

# Install app dependencies
COPY package*.json ./
COPY tsconfig.json ./
COPY src ./src

# Install all dependencies
RUN npm ci

# Compile TypeScript
RUN npm run build

# Remove development dependencies
RUN npm prune --production

# Bundle app source
COPY . .

# Set NODE_ENV to production
ENV NODE_ENV=production

# Port
EXPOSE 8000

# Start the compiled JavaScript code
CMD [ "node", "dist/app.js" ]